### ISSUE TITLE
Publish to supermarket.chef.io

### ISSUE THREAD

**Issue by gamepoet** [adamkrone/chef-consul-template#14]
Do you have any plans on publishing this cookbook to the chef supermarket so it's easier to consume?

**Comment by adamkrone** [comment]
Yes, thanks for bringing this up. I'll look into it this weekend.

**Comment by gamepoet** [comment]
Awesome. Thanks!

**Comment by adamkrone** [comment]
Okay, should be live on the supermarket:

https://supermarket.chef.io/cookbooks/consul-template

**Comment by gamepoet** [comment]
Thanks!
