### ISSUE TITLE
Config dir permissions are getting double-set

### ISSUE THREAD

**Issue by ewr** [adamkrone/chef-consul-template#19]
There are two places in the cookbook that are creating the config dir, and they're setting different permissions...

In the service recipe:

https://github.com/adamkrone/chef-consul-template/blob/adda5d8c691b1f7ad62ec8616eff1815ca58d575/recipes/service.rb#L44-L51

In the config provider:

https://github.com/adamkrone/chef-consul-template/blob/adda5d8c691b1f7ad62ec8616eff1815ca58d575/providers/config.rb#L25-L32

I'm guessing that the 0755 that the service recipe sets is probably correct for the directory, and that the config provider should be using that (and just using `node['consul_template']['template_mode']` for the template config file). As it is now, the config resource is always setting its changed flag, which is causing our wrapper template to restart consul-template unnecessarily.

**Comment by adamkrone** [comment]
Thanks for pointing this out. It should now be fixed on master.

**Comment by ewr** [comment]
Thanks!
