### ISSUE TITLE
golang solution constraint between consul cookbook and consul-template cookbook

### ISSUE THREAD

**Issue by jslusher** [adamkrone/chef-consul-template#22]
depends 'golang', '1.5.0'
```
Unable to satisfy constraints on package golang due to solution constraint....
Solution constraints that may result in a constraint on golang: [(consul = 0.9.0) -> (golang ~> 1.4)]
```

**Comment by adamkrone** [comment]
Strange, I haven't run into this.

Are you sure this is an issue between the consul and consul-template cookbooks? It looks like we're using the same constraint:

https://github.com/adamkrone/chef-consul-template/blob/master/metadata.rb#L21
https://github.com/johnbellone/consul-cookbook/blob/master/metadata.rb#L26

Unless it somehow has to do with '1.4' vs '1.4.0'. That's already a part of PR #21.

Can you include any information on what other cookbooks/versions you're using?

**Comment by lightpriest** [comment]
I had this exact constraint problem. If one installs and uploads consul cookbook (~> 1.4) and only then installs and uploads consul-template (~ 1.4.0), you would end up having golang 1.5.0 on the Chef server.

iirc, I removed golang 1.5.0 from the server and had Berkshelf rebuild the correct dependency tree.

PR #21 should solve this.

**Comment by adamkrone** [comment]
Okay, that makes sense, thanks for the clarification. This should be resolved, so I'll close it.
