### ISSUE TITLE
Updating version does not update the binary

### ISSUE THREAD

**Issue by scalp42** [adamkrone/chef-consul-template#38]
Upgrading does not appear to be upgrading the binary:

```ruby
default['consul_template']['version'] = '0.12.0'
default['consul_template']['checksums']['consul-template_0.12.0_linux_amd64'] = '1fff23fa44fd0af0cb56f011a911af1e9d407a2eeb360f520a503d2f330fdf43'
```

```
Recipe: consul-template::install_binary
  * ark[consul-template] action cherry_pick
    * directory[/usr/local/bin] action create (up to date)
    * remote_file[/var/chef/cache/consul-template.zip] action create
      - create new file /var/chef/cache/consul-template.zip
      - update content in file /var/chef/cache/consul-template.zip from none to 1fff23
      (new content is binary, diff output suppressed)
    * execute[cherry_pick consul-template from /var/chef/cache/consul-template.zip] action nothing (skipped due to action :nothing)
    * execute[set owner on /usr/local/bin] action nothing (skipped due to action :nothing)
    * execute[cherry_pick consul-template from /var/chef/cache/consul-template.zip] action run (up to date)

  * file[/usr/local/bin/consul-template] action touch
    - update utime on file /usr/local/bin/consul-template
```

```
root@i-014fe1d8# consul-template --version
2015/12/18 02:05:07 [DEBUG] (logging) setting up logging
2015/12/18 02:05:07 [DEBUG] (logging) config:

{
  "name": "consul-template",
  "level": "WARN",
  "syslog": false,
  "syslog_facility": "LOCAL0"
}

consul-template v0.10.0
```

**Comment by scalp42** [comment]
Actually if you remove `consul-template` completely, looks like `ark` is messing up somewhere:

```
root@i-014fe1d8# ll /usr/local/bin/consul-template
-rwxr-xr-x 1 root root 0 Dec 18 02:09 /usr/local/bin/consul-template*
```

**Comment by ccannell67** [comment]
Yeah, I believe that is due to using the 'creates' attribute with the 'cherry_pick' action in the ark resource - https://github.com/adamkrone/chef-consul-template/blob/master/recipes/install_binary.rb#L32

using 'creates', keeps the extraction from running every time, since it checks for existence of file.

To handle updates, ark :install should probably be used to install to a versioned path and use a symlink to the binary. 

That or do version checking of the consul-template library.

**Comment by scalp42** [comment]
Going to ping @someara @sigje @tas50,

Should I open an issue in ark ?

**Comment by adamkrone** [comment]
It sounds like we should be symlinking, or using our own guard, as @ccannell67 mentioned.

I should

**Comment by adamkrone** [comment]
@scalp42 I just merged some changes into master that updates the way binaries are downloaded/extracted/etc. I moved away from ark, and it's now using a symlink.

Let me know if this fixes things for you. If everything checks out, I will be releasing a new version on the supermarket soon.

**Comment by scalp42** [comment]
@adamkrone just saw that. Thanks for looking into it.

I'm hoping to tinker with it today or Tuesday!

**Comment by scalp42** [comment]
Testing.

**Comment by scalp42** [comment]
@adamkrone working great! Updated consul-template version itself and the chef-consul-template cookbook version at same time.

:100:

**Comment by scalp42** [comment]
Closing as it's fixed in master.
