### ISSUE TITLE
Current tagged release v0.9.1 is broken for new consul-template v0.12.2

### ISSUE THREAD

**Issue by fstradiotti** [adamkrone/chef-consul-template#44]
Hello, 
i have spotted an error while calling this cookbook inside my wrapper cookbook which took me a while to debug. I have been getting the following key error due to a wrong filename search for it's own checksum. The recipe should be searching for the checksum named 'consul-template...' (with a dash in the middle) but instead it's searching 'consul_template...' (with an underscore) which causes it to throw a key not found error. 

```
key not found: "consul_template_0.12.2_linux_amd64" 
```

After a bit of debugging and trying out this cookbook on itself I released that the fix has already been implemented in the master branch but it hasn't been released yet, hence still erroring when calling this via a wrapper cookbook. 

Could you please create a new tagged release so that I can call this cookbook successfully? 
Thank you

**Comment by mjcdiggity** [comment]
@fstradiotti
Support for `consul_template` 12.x is in latest master but has not yet been released. 
https://github.com/adamkrone/chef-consul-template/blob/master/attributes/checksums.rb#L166-L213

Not sure what the plans are for next release. @adamkrone

**Comment by scalp42** [comment]
@fstradiotti try to point the cookbook to master.

If using Berkshelf, in your `Berksfile`:

```
cookbook 'consul-template', git: 'git@github.com:adamkrone/chef-consul-template.git', ref: '3f978781de48c9bd70e3b863e3f7c0a324a4b26f'
```

**Comment by fstradiotti** [comment]
Thanks for the tip, I pointed the cookbook to the sha commit in my Berksfile like you mentioned and it worked fine. 
Would be good to have an official release soon as the current one is quite outdated!

**Comment by scalp42** [comment]
Glad it helped but yes up to @adamkrone for this :smile:

**Comment by adamkrone** [comment]
@fstradiotti thanks for bringing this up, and thanks @scalp42 for providing a temporary solution. I'm looking to release a new version in the next few days, pending some other PRs that need to get merged.

I'm closing this as it will be resolved once the new version is out.
