### ISSUE TITLE
How to test notification in ChefSpec?

### ISSUE THREAD

**Issue by WarFox** [adamkrone/chef-consul-template#56]
Thanks for making this open source. I'm using this cookbook to setup consul-template for our nginx load balancing.

It works great, but I have a problem trying to test notification of reload using ChefSpec

Here is my `consul_template_config definition`

```
consul_template_config service_name do
  templates [{
    source: '/etc/nginx/nginx.conf.ctmpl',
    destination: '/etc/nginx/nginx.conf',
    command: 'service nginx reload'
  }]
  notifies :reload, 'service[consul-template]', :delayed
end
```

And here is my ChefSpec test

```
    consul_template = chef_run.consul_template_config(service_name)
    expect(consul_template).to notify('service[consul-template]')
      .to(:reload).delayed
```

But I get

```
     Failure/Error: consul_template = chef_run.consul_template_config(service_name)

     NoMethodError:
       undefined method `consul_template_config' for #<ChefSpec::SoloRunner:0x007fcf5ffbf5f0>
```

Am I doing something wrong?

**Comment by adamkrone** [comment]
@WarFox I just added a similar test for this: https://github.com/adamkrone/chef-consul-template/pull/57/files

I needed to add a custom matcher to find the consul_template_config LWRP. If you're pulling from master, you should be able to update to the latest commit and hopefully it will just work. If you're pulling from the supermarket, I probably won't be releasing a new version for a little while, so you'll have to implement the matcher in your own cookbook. You should be able to use the PR linked above for reference.

Let me know if anything is still unclear.

**Comment by adamkrone** [comment]
@WarFox I had to push another fix for the custom matcher, so it's only included when we're running ChefSpec: https://github.com/adamkrone/chef-consul-template/commit/8e77bea3fb1d9a9c499542ffe3249fd0dbeef115

**Comment by WarFox** [comment]
@adamkrone Sorry for late reply

Thanks for the answer. I'm happy with adding custom matcher to my cookbook for now.

Have you had a look at Poise library? It can automatically add ChefSpec matchers for resources.
https://github.com/poise/poise/blob/master/lib/poise/helpers/chefspec_matchers.rb
[consul-cookbook](https://github.com/johnbellone/consul-cookbook) uses it. Might be handy

I checked your commit [8e77bea](https://github.com/adamkrone/chef-consul-template/commit/8e77bea3fb1d9a9c499542ffe3249fd0dbeef115), have one suggestion from Sethvargo's original documentation.

https://github.com/sethvargo/chefspec#packaging-custom-matchers
> 
> The entire contents of this file must be wrapped with the conditional clause checking if ChefSpec is defined.

**Comment by adamkrone** [comment]
@WarFox I'll take a look at Poise, and thanks for the link about packaging custom matchers. I'll close this when I make that fix.
