### ISSUE TITLE
broken compatibility with Chef 12

### ISSUE THREAD

**Issue by bobchaos** [adamkrone/chef-consul-template#82]
commit 5c957f775482f3a55c97447f7fe5aaf92193ecb8 broke compatibility with Chef 12's ruby version by modifying libraries/consul-template_helpers.rb line 25 to use the new .match? method.

I see someone already opened PR 81 which would fix this issue. Thanks!

**Comment by oscar123mendoza** [comment]
What this every fixed?

**Comment by adamkrone** [comment]
This has been merged into master. I'll be doing a release to the supermarket once I take care of some other outstanding issues.

**Comment by xblitz** [comment]
Any news for a new version?  I would enjoy having this fix ^^
